/* ── Page Styles ─────────────────────────────────── */
export const s = {
    page: {
        display: 'flex',
        flexDirection: 'column',
        gap: 32,
        animation: 'aigenSettingsFadeIn 0.2s ease both',
    },
    pageHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 14,
    },
    pageHeaderIcon: {
        width: 42, height: 42,
        borderRadius: 10,
        background: 'linear-gradient(135deg, rgba(99,102,241,0.2), rgba(20,184,166,0.15))',
        border: '1px solid rgba(99,102,241,0.2)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        color: '#818cf8',
        flexShrink: 0,
        marginTop: 2,
    },
    pageTitle: {
        margin: '0 0 4px',
        fontSize: '1.05rem',
        fontWeight: 700,
        color: 'var(--text-primary)',
    },
    pageDesc: {
        margin: 0,
        fontSize: '0.845rem',
        color: 'var(--text-secondary)',
        lineHeight: 1.6,
        maxWidth: 580,
    },
    section: {
        display: 'flex',
        flexDirection: 'column',
        gap: 14,
    },
    sectionHead: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    sectionHeadLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
    },
    sectionDot: {
        width: 6, height: 6,
        borderRadius: '50%',
        background: 'linear-gradient(135deg, #6366f1, #14b8a6)',
        flexShrink: 0,
    },
    sectionTitle: {
        margin: 0,
        fontSize: '0.9rem',
        fontWeight: 700,
        color: 'var(--text-primary)',
    },
    sectionCount: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 20, height: 20,
        padding: '0 6px',
        borderRadius: 10,
        background: 'rgba(99,102,241,0.15)',
        border: '1px solid rgba(99,102,241,0.2)',
        fontSize: '0.7rem',
        fontWeight: 700,
        color: '#818cf8',
    },
    addBtn: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        fontSize: '0.82rem',
        padding: '5px 12px',
    },
    loadingState: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '20px 0',
        color: 'var(--text-secondary)',
        fontSize: '0.875rem',
    },
    loadingSpinner: {
        display: 'inline-block',
        width: 14, height: 14,
        border: '2px solid var(--border-color)',
        borderTopColor: 'var(--accent-indigo)',
        borderRadius: '50%',
        animation: 'spin 0.7s linear infinite',
    },
    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
        padding: '36px 20px',
        borderRadius: 12,
        border: '1px dashed var(--border-color)',
        background: 'rgba(255,255,255,0.01)',
        gap: 8,
    },
    emptyIcon: {
        width: 48, height: 48,
        borderRadius: 12,
        background: 'rgba(99,102,241,0.08)',
        border: '1px solid rgba(99,102,241,0.15)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        color: '#818cf8',
        marginBottom: 4,
    },
    emptyTitle: {
        margin: 0,
        fontSize: '0.925rem',
        fontWeight: 600,
        color: 'var(--text-primary)',
    },
    emptyDesc: {
        margin: 0,
        fontSize: '0.845rem',
        color: 'var(--text-secondary)',
        maxWidth: 340,
        lineHeight: 1.6,
    },
    providerList: {
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
    },
    providerCard: {
        borderRadius: 10,
        border: '1px solid var(--border-color)',
        borderLeft: '3px solid',
        background: 'var(--bg-tertiary)',
        padding: '14px 16px',
        transition: 'all 0.15s',
        className: 'aigen-provider-card',
    },
    cardMain: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 12,
    },
    providerAvatar: {
        width: 34, height: 34,
        borderRadius: 8,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: '0.95rem',
        fontWeight: 800,
        flexShrink: 0,
    },
    providerNameRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 7,
        flexWrap: 'wrap',
        marginBottom: 5,
    },
    providerName: {
        fontWeight: 600,
        fontSize: '0.925rem',
        color: 'var(--text-primary)',
    },
    defaultBadge: {
        fontSize: '0.68rem',
        fontWeight: 700,
        color: '#818cf8',
        background: 'rgba(99,102,241,0.15)',
        border: '1px solid rgba(99,102,241,0.25)',
        padding: '1px 7px',
        borderRadius: 20,
        letterSpacing: '0.02em',
    },
    disabledBadge: {
        fontSize: '0.68rem',
        fontWeight: 700,
        color: '#f87171',
        background: 'rgba(239,68,68,0.1)',
        border: '1px solid rgba(239,68,68,0.2)',
        padding: '1px 7px',
        borderRadius: 20,
    },
    providerMeta: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
        flexWrap: 'wrap',
    },
    metaChip: {
        fontSize: '0.75rem',
        color: 'var(--text-secondary)',
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid var(--border-color)',
        padding: '1px 7px',
        borderRadius: 4,
    },
    metaDot: {
        color: 'var(--border-color)',
        fontSize: '0.75rem',
        userSelect: 'none',
    },
    testResult: {
        marginTop: 8,
        padding: '5px 10px',
        borderRadius: 6,
        fontSize: '0.78rem',
        border: '1px solid',
        fontWeight: 500,
    },
    cardActions: {
        display: 'flex',
        gap: 4,
        flexShrink: 0,
        alignItems: 'center',
    },
    iconBtn: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
        padding: '5px 9px',
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid var(--border-color)',
        borderRadius: 6,
        color: 'var(--text-secondary)',
        fontSize: '0.75rem',
        cursor: 'pointer',
        transition: 'all 0.15s',
        fontFamily: 'inherit',
        fontWeight: 500,
        className: 'aigen-icon-btn',
    },
    iconBtnActive: {
        borderColor: 'rgba(99,102,241,0.3)',
        color: '#818cf8',
    },
    iconBtnDanger: {
        className: 'aigen-icon-btn aigen-icon-btn-danger',
    },
    iconBtnLabel: {
        fontSize: '0.75rem',
    },
    miniSpinner: {
        display: 'inline-block',
        width: 11, height: 11,
        border: '1.5px solid var(--border-color)',
        borderTopColor: 'var(--accent-indigo)',
        borderRadius: '50%',
        animation: 'spin 0.7s linear infinite',
        flexShrink: 0,
    },
    modifiedBadge: {
        fontSize: '0.7rem',
        fontWeight: 600,
        color: '#fbbf24',
        background: 'rgba(234,179,8,0.1)',
        border: '1px solid rgba(234,179,8,0.2)',
        padding: '1px 8px',
        borderRadius: 20,
    },
    templateTypeBadge: {
        fontSize: '0.68rem',
        fontWeight: 700,
        color: '#14b8a6',
        background: 'rgba(20,184,166,0.1)',
        border: '1px solid rgba(20,184,166,0.2)',
        padding: '1px 8px',
        borderRadius: 20,
        letterSpacing: '0.02em',
    },
    templateDesc: {
        margin: 0,
        fontSize: '0.845rem',
        color: 'var(--text-secondary)',
        lineHeight: 1.6,
    },
    varChips: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 6,
    },
    varChip: {
        fontSize: '0.75rem',
        fontFamily: 'monospace',
        color: '#818cf8',
        background: 'rgba(99,102,241,0.1)',
        border: '1px solid rgba(99,102,241,0.2)',
        padding: '2px 8px',
        borderRadius: 5,
        userSelect: 'all',
    },
    editorWrap: {
        borderRadius: 10,
        border: '1px solid var(--border-color)',
        overflow: 'hidden',
        background: 'var(--bg-primary)',
    },
    readOnlyBanner: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        padding: '7px 14px',
        background: 'rgba(255,255,255,0.03)',
        borderBottom: '1px solid var(--border-color)',
        fontSize: '0.78rem',
        color: 'var(--text-secondary)',
    },
    editor: {
        width: '100%',
        minHeight: 260,
        fontFamily: '"SF Mono", "Fira Code", "Cascadia Code", monospace',
        fontSize: '0.8rem',
        resize: 'vertical',
        lineHeight: 1.65,
        border: 'none',
        borderRadius: 0,
        background: 'transparent',
        padding: '14px',
        boxSizing: 'border-box',
    },
    editorFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        padding: '6px 12px',
        borderTop: '1px solid var(--border-color)',
        background: 'rgba(255,255,255,0.02)',
    },
    charCount: {
        fontSize: '0.72rem',
        color: 'var(--text-secondary)',
        fontFamily: 'monospace',
        opacity: 0.6,
    },
};

/* ── Modal Styles ─────────────────────────────────── */
export const m = {
    backdrop: {
        position: 'fixed', inset: 0,
        background: 'rgba(0,0,0,0.65)',
        backdropFilter: 'blur(6px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        zIndex: 1000, padding: 16,
    },
    modal: {
        width: '100%',
        maxWidth: 520,
        maxHeight: '92vh',
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border-color)',
        borderRadius: 14,
        boxShadow: '0 32px 80px rgba(0,0,0,0.6)',
        overflow: 'hidden',
        animation: 'aigenSettingsFadeIn 0.2s ease both',
    },
    accentBar: {
        height: 3,
        flexShrink: 0,
    },
    header: {
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 12,
        padding: '16px 20px 14px',
        borderBottom: '1px solid var(--border-color)',
        flexShrink: 0,
    },
    providerInitial: {
        width: 36, height: 36,
        borderRadius: 8,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: '1rem',
        fontWeight: 800,
        flexShrink: 0,
    },
    modalTitle: {
        margin: '0 0 2px',
        fontSize: '0.95rem',
        fontWeight: 700,
    },
    modalSub: {
        margin: 0,
        fontSize: '0.78rem',
        color: 'var(--text-secondary)',
    },
    closeBtn: {
        width: 28, height: 28,
        borderRadius: 6,
        border: 'none',
        background: 'none',
        color: 'var(--text-secondary)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        cursor: 'pointer',
        flexShrink: 0,
        transition: 'all 0.15s',
    },
    formBody: {
        flex: 1,
        overflowY: 'auto',
        padding: '18px 20px',
        display: 'flex',
        flexDirection: 'column',
        gap: 16,
    },
    typeGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: 8,
    },
    typeCard: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 5,
        padding: '10px 6px',
        borderRadius: 8,
        border: '1px solid',
        cursor: 'pointer',
        transition: 'all 0.15s',
        fontFamily: 'inherit',
        className: 'aigen-type-card',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: 6,
    },
    fieldLabel: {
        fontSize: '0.78rem',
        fontWeight: 600,
        color: 'var(--text-secondary)',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    required: {
        color: 'var(--accent-red)',
        marginLeft: 2,
    },
    chip: {
        fontSize: '0.68rem',
        fontWeight: 600,
        color: 'var(--text-secondary)',
        background: 'rgba(255,255,255,0.05)',
        border: '1px solid var(--border-color)',
        padding: '1px 6px',
        borderRadius: 4,
    },
    currentKeyNote: {
        fontSize: '0.76rem',
        color: 'var(--text-secondary)',
        padding: '5px 10px',
        background: 'rgba(255,255,255,0.03)',
        border: '1px solid var(--border-color)',
        borderRadius: 6,
    },
    toggle: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        cursor: 'pointer',
        userSelect: 'none',
    },
    checkbox: {
        width: 16, height: 16,
        cursor: 'pointer',
    },
    toggleLabel: {
        fontSize: '0.875rem',
        fontWeight: 500,
        color: 'var(--text-primary)',
    },
    footer: {
        display: 'flex',
        gap: 8,
        justifyContent: 'flex-end',
        paddingTop: 4,
        borderTop: '1px solid var(--border-color)',
        marginTop: 4,
    },
    deleteIcon: {
        width: 44, height: 44,
        borderRadius: 10,
        background: 'rgba(239,68,68,0.1)',
        border: '1px solid rgba(239,68,68,0.2)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        color: '#f87171',
        marginBottom: 14,
    },
};
